### ISSUE TITLE
[Pimcore 11 / Bug] Admin UI light theme does not contrast with icons

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/web-to-print-bundle#62] opened 2024-02-22 15:58 UTC
Related: https://github.com/coreshop/CoreShop/issues/2566

Some icons like:
![image](https://github.com/pimcore/web-to-print-bundle/assets/279826/5fdbaf78-6a25-4b8e-9412-5dd2edae2895)

And on hover:
![image](https://github.com/pimcore/web-to-print-bundle/assets/279826/f3092e6f-d648-4b2c-8961-81b9b07b6f6f)

... are not compatible with the Admin UI Light theme.

**Comment by kingjia90** [comment] 2024-02-29 07:18
Thank you for reporting!

Duplicate of https://github.com/pimcore/admin-ui-classic-light-theme-bundle/issues/4#issuecomment-1832101851
Fixed by https://github.com/pimcore/admin-ui-classic-light-theme-bundle/pull/9

**Closed as not planned by kingjia90** 2024-02-29 07:18 UTC

**Comment by NiklasBr** [comment] 2024-02-29 07:33
404 errors on those links.

**Comment by kingjia90** [comment] 2024-02-29 07:35
Ah sorry, they are in private repos
![image](https://github.com/pimcore/web-to-print-bundle/assets/6014195/961404a8-03ee-4842-9b88-cf1d146d36a4)
but good news is that it will be tagged light-theme `1.0.2` today with the fix

**Comment by NiklasBr** [comment] 2024-02-29 07:37
Wouldn't it be a lot easier if paying enterprise customers were given access to report these issues as well as issues with other enterprise bundles in their respective repositories?

**Comment by kingjia90** [comment] 2024-02-29 07:46
I have no idea as it falls out my direct responsibility (repository settings and SLA stuff), but personally speaking, i am with you on that, i prefer to work directly dev-to-dev on issues/pr instead of getting through jira ticket but the Enterprise World doesn't seem rotating like that 😅

**Comment by NiklasBr** [comment] 2024-03-05 16:38
> […] but good news is that it will be tagged light-theme `1.0.2` today with the fix

@kingjia90 can you update [the documentation](https://pimcore.com/docs/platform/Light_Theme_Admin_UI/) to show how we should replicate the fix in Bundles not made by Pimcore?

**Comment by kingjia90** [comment] 2024-03-05 18:17
My hands are tied, unless there's an enteprise ticket behind it, the max i can do is open the issue for it, i've also opened one for a class to `<body>` element to be able to target light theme "natively" in css

**Comment by NiklasBr** [comment] 2024-03-05 20:11
So it was only halfway fixed?

**Comment by kingjia90** [comment] 2024-03-05 22:53
more like not top-priority, unless given different directives
